version: "3"

services:
  app: # Name of the service.
    build: . # Use the Dockerfile in the current directory.
    ports:
      # Bind the host's port to the container's port - "<host>:<container>".
      # Create-react-app uses port 3000 by default, change the first number if that port isn't
      # available on your machine.
      - "3000:3000"
    volumes:
      # Mount the current folder to the container, the means any local changes are reflected in
      # the container and vice versa.
      - ./:/home/node/app/
      # Don't mount the .git/ or node_modules/ folders.
      - /home/node/app/.git
      - /home/node/app/node_modules
